[package]
name = "algjsl"
version = "0.1.0"
authors = ["dafer <dafernandezperez@gmail.com>"]
edition = "2024"

[dependencies]

# Local crates
perf_macro = {path="../perf_macro"} # Macro to measure performance
utils = {path="../utils"}           # Utils common to the project

# Shared from the workspace
chrono.workspace = true             
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
dotenvy.workspace = true
polars.workspace = true

# Backend calculations specific
tokio = {version="1.44.2", features=["full"]}
sqlx = {version="0.8.5", features = ["sqlite", "runtime-tokio-native-tls", "uuid", "chrono", "json"] }
argon2 = {version="0.5.3", features=["rand"]}
thiserror = "2.0.12"
rand = "0.9.0"
base64 = "0.22.1"
