# ./pmm-frontend/Cargo.toml

[package]
name = "pmm-frontend"
version = "0.1.0"
authors = ["Daniel Perez <daniel.perez@pmmgt.com>"]
edition = "2024"

[dependencies]

# Local crates
pmm-perf = {path="../pmm-perf"} # Macro to measure pmm-performance
# pmm-utils = {path="../pmm-utils"}           # pmm-utils common to the project
# pmm-core = {path="../pmm-core"}

# External crates
dioxus = { version = "0.7.3", features = [] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
